# Generated by Django 5.2 on 2025-05-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_image_tag_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
    ]
